<?php
/**
 * PeppolIdentifiersApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Storecove API
 *
 * Storecove API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: apisupport@storecove.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * PeppolIdentifiersApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PeppolIdentifiersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createPeppolIdentifier
     *
     * Create a new PeppolIdentifier
     *
     * @param  int $legal_entity_id The id of the LegalEntity for which to create the PeppolIdentifier (required)
     * @param  \Swagger\Client\Model\PeppolIdentifierCreate $peppol_identifier PeppolIdentifier to create (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\PeppolIdentifier
     */
    public function createPeppolIdentifier($legal_entity_id, $peppol_identifier)
    {
        list($response) = $this->createPeppolIdentifierWithHttpInfo($legal_entity_id, $peppol_identifier);
        return $response;
    }

    /**
     * Operation createPeppolIdentifierWithHttpInfo
     *
     * Create a new PeppolIdentifier
     *
     * @param  int $legal_entity_id The id of the LegalEntity for which to create the PeppolIdentifier (required)
     * @param  \Swagger\Client\Model\PeppolIdentifierCreate $peppol_identifier PeppolIdentifier to create (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\PeppolIdentifier, HTTP status code, HTTP response headers (array of strings)
     */
    public function createPeppolIdentifierWithHttpInfo($legal_entity_id, $peppol_identifier)
    {
        $returnType = '\Swagger\Client\Model\PeppolIdentifier';
        $request = $this->createPeppolIdentifierRequest($legal_entity_id, $peppol_identifier);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\PeppolIdentifier',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ErrorModel[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createPeppolIdentifierAsync
     *
     * Create a new PeppolIdentifier
     *
     * @param  int $legal_entity_id The id of the LegalEntity for which to create the PeppolIdentifier (required)
     * @param  \Swagger\Client\Model\PeppolIdentifierCreate $peppol_identifier PeppolIdentifier to create (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createPeppolIdentifierAsync($legal_entity_id, $peppol_identifier)
    {
        return $this->createPeppolIdentifierAsyncWithHttpInfo($legal_entity_id, $peppol_identifier)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createPeppolIdentifierAsyncWithHttpInfo
     *
     * Create a new PeppolIdentifier
     *
     * @param  int $legal_entity_id The id of the LegalEntity for which to create the PeppolIdentifier (required)
     * @param  \Swagger\Client\Model\PeppolIdentifierCreate $peppol_identifier PeppolIdentifier to create (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createPeppolIdentifierAsyncWithHttpInfo($legal_entity_id, $peppol_identifier)
    {
        $returnType = '\Swagger\Client\Model\PeppolIdentifier';
        $request = $this->createPeppolIdentifierRequest($legal_entity_id, $peppol_identifier);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createPeppolIdentifier'
     *
     * @param  int $legal_entity_id The id of the LegalEntity for which to create the PeppolIdentifier (required)
     * @param  \Swagger\Client\Model\PeppolIdentifierCreate $peppol_identifier PeppolIdentifier to create (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createPeppolIdentifierRequest($legal_entity_id, $peppol_identifier)
    {
        // verify the required parameter 'legal_entity_id' is set
        if ($legal_entity_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $legal_entity_id when calling createPeppolIdentifier'
            );
        }
        // verify the required parameter 'peppol_identifier' is set
        if ($peppol_identifier === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $peppol_identifier when calling createPeppolIdentifier'
            );
        }

        $resourcePath = '/legal_entities/{legal_entity_id}/peppol_identifiers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($legal_entity_id !== null) {
            $resourcePath = str_replace(
                '{' . 'legal_entity_id' . '}',
                ObjectSerializer::toPathValue($legal_entity_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($peppol_identifier)) {
            $_tempBody = $peppol_identifier;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deletePeppolIdentifier
     *
     * Delete PeppolIdentifier
     *
     * @param  int $legal_entity_id The id of the LegalEntity this PeppolIdentifier belongs to (required)
     * @param  string $superscheme The superscheme of the identifier. Should always be \&quot;iso6523-actorid-upis\&quot;. (required)
     * @param  string $scheme PEPPOL identifier scheme id, e.g. \&quot;DE:VAT\&quot;. For a full list see &lt;&lt;peppol_schemes_list&gt;&gt;. (required)
     * @param  string $identifier PEPPOL identifier (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deletePeppolIdentifier($legal_entity_id, $superscheme, $scheme, $identifier)
    {
        $this->deletePeppolIdentifierWithHttpInfo($legal_entity_id, $superscheme, $scheme, $identifier);
    }

    /**
     * Operation deletePeppolIdentifierWithHttpInfo
     *
     * Delete PeppolIdentifier
     *
     * @param  int $legal_entity_id The id of the LegalEntity this PeppolIdentifier belongs to (required)
     * @param  string $superscheme The superscheme of the identifier. Should always be \&quot;iso6523-actorid-upis\&quot;. (required)
     * @param  string $scheme PEPPOL identifier scheme id, e.g. \&quot;DE:VAT\&quot;. For a full list see &lt;&lt;peppol_schemes_list&gt;&gt;. (required)
     * @param  string $identifier PEPPOL identifier (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deletePeppolIdentifierWithHttpInfo($legal_entity_id, $superscheme, $scheme, $identifier)
    {
        $returnType = '';
        $request = $this->deletePeppolIdentifierRequest($legal_entity_id, $superscheme, $scheme, $identifier);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deletePeppolIdentifierAsync
     *
     * Delete PeppolIdentifier
     *
     * @param  int $legal_entity_id The id of the LegalEntity this PeppolIdentifier belongs to (required)
     * @param  string $superscheme The superscheme of the identifier. Should always be \&quot;iso6523-actorid-upis\&quot;. (required)
     * @param  string $scheme PEPPOL identifier scheme id, e.g. \&quot;DE:VAT\&quot;. For a full list see &lt;&lt;peppol_schemes_list&gt;&gt;. (required)
     * @param  string $identifier PEPPOL identifier (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deletePeppolIdentifierAsync($legal_entity_id, $superscheme, $scheme, $identifier)
    {
        return $this->deletePeppolIdentifierAsyncWithHttpInfo($legal_entity_id, $superscheme, $scheme, $identifier)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deletePeppolIdentifierAsyncWithHttpInfo
     *
     * Delete PeppolIdentifier
     *
     * @param  int $legal_entity_id The id of the LegalEntity this PeppolIdentifier belongs to (required)
     * @param  string $superscheme The superscheme of the identifier. Should always be \&quot;iso6523-actorid-upis\&quot;. (required)
     * @param  string $scheme PEPPOL identifier scheme id, e.g. \&quot;DE:VAT\&quot;. For a full list see &lt;&lt;peppol_schemes_list&gt;&gt;. (required)
     * @param  string $identifier PEPPOL identifier (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deletePeppolIdentifierAsyncWithHttpInfo($legal_entity_id, $superscheme, $scheme, $identifier)
    {
        $returnType = '';
        $request = $this->deletePeppolIdentifierRequest($legal_entity_id, $superscheme, $scheme, $identifier);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deletePeppolIdentifier'
     *
     * @param  int $legal_entity_id The id of the LegalEntity this PeppolIdentifier belongs to (required)
     * @param  string $superscheme The superscheme of the identifier. Should always be \&quot;iso6523-actorid-upis\&quot;. (required)
     * @param  string $scheme PEPPOL identifier scheme id, e.g. \&quot;DE:VAT\&quot;. For a full list see &lt;&lt;peppol_schemes_list&gt;&gt;. (required)
     * @param  string $identifier PEPPOL identifier (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deletePeppolIdentifierRequest($legal_entity_id, $superscheme, $scheme, $identifier)
    {
        // verify the required parameter 'legal_entity_id' is set
        if ($legal_entity_id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $legal_entity_id when calling deletePeppolIdentifier'
            );
        }
        // verify the required parameter 'superscheme' is set
        if ($superscheme === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $superscheme when calling deletePeppolIdentifier'
            );
        }
        // verify the required parameter 'scheme' is set
        if ($scheme === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $scheme when calling deletePeppolIdentifier'
            );
        }
        // verify the required parameter 'identifier' is set
        if ($identifier === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $identifier when calling deletePeppolIdentifier'
            );
        }

        $resourcePath = '/legal_entities/{legal_entity_id}/peppol_identifiers/{superscheme}/{scheme}/{identifier}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($legal_entity_id !== null) {
            $resourcePath = str_replace(
                '{' . 'legal_entity_id' . '}',
                ObjectSerializer::toPathValue($legal_entity_id),
                $resourcePath
            );
        }
        // path params
        if ($superscheme !== null) {
            $resourcePath = str_replace(
                '{' . 'superscheme' . '}',
                ObjectSerializer::toPathValue($superscheme),
                $resourcePath
            );
        }
        // path params
        if ($scheme !== null) {
            $resourcePath = str_replace(
                '{' . 'scheme' . '}',
                ObjectSerializer::toPathValue($scheme),
                $resourcePath
            );
        }
        // path params
        if ($identifier !== null) {
            $resourcePath = str_replace(
                '{' . 'identifier' . '}',
                ObjectSerializer::toPathValue($identifier),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
