<?php
/**
 * InvoiceLineTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Storecove API
 *
 * Storecove API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: apisupport@storecove.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InvoiceLineTest Class Doc Comment
 *
 * @category    Class */
// * @description InvoiceLine
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceLineTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InvoiceLine"
     */
    public function testInvoiceLine()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "invoice_period"
     */
    public function testPropertyInvoicePeriod()
    {
    }

    /**
     * Test attribute "item_price"
     */
    public function testPropertyItemPrice()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "quantity_unit_code"
     */
    public function testPropertyQuantityUnitCode()
    {
    }

    /**
     * Test attribute "allowance_charge"
     */
    public function testPropertyAllowanceCharge()
    {
    }

    /**
     * Test attribute "amount_excluding_vat"
     */
    public function testPropertyAmountExcludingVat()
    {
    }

    /**
     * Test attribute "tax"
     */
    public function testPropertyTax()
    {
    }

    /**
     * Test attribute "accounting_cost"
     */
    public function testPropertyAccountingCost()
    {
    }

    /**
     * Test attribute "accounting_cost_code"
     */
    public function testPropertyAccountingCostCode()
    {
    }

    /**
     * Test attribute "delivery"
     */
    public function testPropertyDelivery()
    {
    }

    /**
     * Test attribute "sellers_item_identification"
     */
    public function testPropertySellersItemIdentification()
    {
    }

    /**
     * Test attribute "standard_item_identification"
     */
    public function testPropertyStandardItemIdentification()
    {
    }

    /**
     * Test attribute "standard_item_identification_scheme_id"
     */
    public function testPropertyStandardItemIdentificationSchemeId()
    {
    }

    /**
     * Test attribute "standard_item_identification_scheme_agency_id"
     */
    public function testPropertyStandardItemIdentificationSchemeAgencyId()
    {
    }
}
