<?php
/**
 * PurchaseInvoiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Storecove API
 *
 * Storecove API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: apisupport@storecove.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PurchaseInvoiceTest Class Doc Comment
 *
 * @category    Class */
// * @description PurchaseInvoice
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PurchaseInvoiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PurchaseInvoice"
     */
    public function testPurchaseInvoice()
    {
    }

    /**
     * Test attribute "guid"
     */
    public function testPropertyGuid()
    {
    }

    /**
     * Test attribute "legal_entity_id"
     */
    public function testPropertyLegalEntityId()
    {
    }

    /**
     * Test attribute "external_user_id"
     */
    public function testPropertyExternalUserId()
    {
    }

    /**
     * Test attribute "external_key"
     */
    public function testPropertyExternalKey()
    {
    }

    /**
     * Test attribute "document"
     */
    public function testPropertyDocument()
    {
    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {
    }

    /**
     * Test attribute "issue_date"
     */
    public function testPropertyIssueDate()
    {
    }

    /**
     * Test attribute "tax_point_date"
     */
    public function testPropertyTaxPointDate()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "document_currency_code"
     */
    public function testPropertyDocumentCurrencyCode()
    {
    }

    /**
     * Test attribute "vat_reverse_charge"
     */
    public function testPropertyVatReverseCharge()
    {
    }

    /**
     * Test attribute "amount_including_vat"
     */
    public function testPropertyAmountIncludingVat()
    {
    }

    /**
     * Test attribute "allowance_charge"
     */
    public function testPropertyAllowanceCharge()
    {
    }

    /**
     * Test attribute "payable_rounding_amount"
     */
    public function testPropertyPayableRoundingAmount()
    {
    }

    /**
     * Test attribute "payable_amount"
     */
    public function testPropertyPayableAmount()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "sender"
     */
    public function testPropertySender()
    {
    }

    /**
     * Test attribute "invoice_type"
     */
    public function testPropertyInvoiceType()
    {
    }

    /**
     * Test attribute "period_start"
     */
    public function testPropertyPeriodStart()
    {
    }

    /**
     * Test attribute "period_end"
     */
    public function testPropertyPeriodEnd()
    {
    }

    /**
     * Test attribute "buyer_reference"
     */
    public function testPropertyBuyerReference()
    {
    }

    /**
     * Test attribute "billing_reference"
     */
    public function testPropertyBillingReference()
    {
    }

    /**
     * Test attribute "contract_document_reference"
     */
    public function testPropertyContractDocumentReference()
    {
    }

    /**
     * Test attribute "invoice_lines"
     */
    public function testPropertyInvoiceLines()
    {
    }

    /**
     * Test attribute "accounting"
     */
    public function testPropertyAccounting()
    {
    }

    /**
     * Test attribute "payment_means"
     */
    public function testPropertyPaymentMeans()
    {
    }
}
