<?php
/**
 * ShopAccountResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Storecove API
 *
 * Storecove API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: apisupport@storecove.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ShopAccountResultTest Class Doc Comment
 *
 * @category    Class */
// * @description ShopAccountResult
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShopAccountResultTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShopAccountResult"
     */
    public function testShopAccountResult()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {
    }

    /**
     * Test attribute "external_user_id"
     */
    public function testPropertyExternalUserId()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "from_date"
     */
    public function testPropertyFromDate()
    {
    }

    /**
     * Test attribute "sign_in_error_confirmed"
     */
    public function testPropertySignInErrorConfirmed()
    {
    }

    /**
     * Test attribute "sign_in_error_confirmed_at"
     */
    public function testPropertySignInErrorConfirmedAt()
    {
    }

    /**
     * Test attribute "shop"
     */
    public function testPropertyShop()
    {
    }
}
