<?php
/**
 * LegalEntitiesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Storecove API
 *
 * Storecove API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: apisupport@storecove.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * LegalEntitiesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LegalEntitiesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createLegalEntity
     *
     * Create a new LegalEntity.
     *
     */
    public function testCreateLegalEntity()
    {
    }

    /**
     * Test case for deleteLegalEntity
     *
     * Delete LegalEntity.
     *
     */
    public function testDeleteLegalEntity()
    {
    }

    /**
     * Test case for getLegalEntity
     *
     * Get LegalEntity.
     *
     */
    public function testGetLegalEntity()
    {
    }

    /**
     * Test case for updateLegalEntity
     *
     * Update LegalEntity.
     *
     */
    public function testUpdateLegalEntity()
    {
    }
}
