<?php
/**
 * ShopAccountsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Storecove API
 *
 * Storecove API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: apisupport@storecove.nl
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ShopAccountsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ShopAccountsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createShopAccount
     *
     * Create ShopAccount.
     *
     */
    public function testCreateShopAccount()
    {
    }

    /**
     * Test case for deleteShopAccount
     *
     * Delete ShopAccount.
     *
     */
    public function testDeleteShopAccount()
    {
    }

    /**
     * Test case for getShopAccount
     *
     * Get ShopAccount.
     *
     */
    public function testGetShopAccount()
    {
    }

    /**
     * Test case for shopAccountsAuthFailures
     *
     * Get ShopAccounts with authorization failures.
     *
     */
    public function testShopAccountsAuthFailures()
    {
    }

    /**
     * Test case for shopAccountsIndex
     *
     * Get ShopAccounts for an entity.
     *
     */
    public function testShopAccountsIndex()
    {
    }

    /**
     * Test case for updateShopAccount
     *
     * Update ShopAccount.
     *
     */
    public function testUpdateShopAccount()
    {
    }
}
